package com.michaeltroger.datarecording.controller;


import android.app.IntentService;
import android.content.Intent;
import android.util.Log;

import com.michaeltroger.datarecording.sensor.SensorUtilities;

/**
 * Handles clicks on the notification
 * while recording is active.
 * The app can be running in background
 */
public class NotificationActionService extends IntentService {
    private static final String TAG = NotificationActionService.class.getSimpleName();

    /**
     * Only listen for actions of type command
     */
    public static final String NOTIFICATION_ACTION = "command";
    /**
     * The command to stop the recording with
     */
    public static final String NOTIFICATION_STOP_COMMAND = "stop";

    /**
     * An instance is generated by the Android framework
     * no need to create an object yourself
     */
    public NotificationActionService() {
        super("NotificationAction");
    }

    @Override
    protected void onHandleIntent(final Intent intent) {
        final String command = intent.getStringExtra(NOTIFICATION_ACTION);
        Log.d(TAG, "Received command "+ command +" from notification action");

        switch (command) {
            case NOTIFICATION_STOP_COMMAND:
                SensorUtilities.stopRecording(getApplicationContext());
                break;
            default:
                throw new UnsupportedOperationException();
        }
    }

}
